name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
